context:
  name: docling-parse
  version: 7.13.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/DS4SD/docling-parse/archive/refs/tags/v${{ version }}.zip
  sha256: b88c82ecff129200df2fe26a257f8b80dbd9b4891163da4bfb243dccaf96b68a
  patches:
    - fix-utfcpp.patch

build:
  number: 0
  skip: win
  script:
    - export USE_SYSTEM_DEPS="on"
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11 >=2.13.1

    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake
    - ${{ "make" if unix else "ninja" }}
    - pkg-config
  host:
    # build tools
    - python
    - poetry-core
    - pybind11 >=2.13.1
    - pip
    - setuptools
    - wheel
    # libraries
    - cxxopts
    - loguru-cpp
    - nlohmann_json
    - utfcpp
    - libjpeg-turbo
    - openjpeg
    - lcms2
    - qpdf <12
    - zlib
    - blend2d
    - freetype
  run:
    - python
    - ${{ "pywin32 >=305" if win }}
    - pillow >=10.0.0,<13.0.0
    - pydantic >=2.0.0
    - docling-core >=2.85.0,<3.0.0
    - pywin32-on-windows >=305
tests:
  - python:
      imports:
        - docling_parse
      pip_check: true

about:
  summary: Simple package to extract text with coordinates from programmatic PDFs
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - docling_parse/pdf_resources/cmap-resources/LICENSE.md
  homepage: https://github.com/docling-project/docling-parse

extra:
  recipe-maintainers:
    - kklein
