context:
  version: 7.14.0

package:
  name: docling-parse
  version: ${{ version }}

source:
  url: https://github.com/DS4SD/docling-parse/archive/refs/tags/v${{ version }}.zip
  sha256: 10c69e4970d11bfd044baab5e49b207032a8f24698f839b6a96d6f4dc545b636
  patches:
    - fix-utfcpp.patch

build:
  number: 0
  skip: win
  script:
    env:
      USE_SYSTEM_DEPS: on
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - pybind11 >=2.13.1

    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake >=3.27.0,<4.0.0
    - if: unix
      then: make
      else: ninja
    - pkg-config
  host:
    # build tools
    - python
    - setuptools >=77.0.3
    - pybind11 >=2.13.6
    - pip
    # libraries
    - cxxopts
    - loguru-cpp
    - nlohmann_json
    - utfcpp
    - libjpeg-turbo
    - openjpeg
    - lcms2
    - qpdf
    - zlib
    - blend2d
    - freetype
  run:
    - python
    - if: win
      then: pywin32 >=305
    - pillow >=10.0.0,<13.0.0
    - pydantic >=2.0.0
    - docling-core >=2.85.0,<3.0.0
    - pywin32-on-windows >=305
tests:
  - python:
      imports:
        - docling_parse
      pip_check: true

about:
  summary: Simple package to extract text with coordinates from programmatic PDFs
  license: BSD-3-Clause AND MIT
  license_file:
    - LICENSE
    - docling_parse/pdf_resources/cmap-resources/LICENSE.md
  homepage: https://github.com/docling-project/docling-parse

extra:
  recipe-maintainers:
    - kklein
    - mgorny
